package database;

import java.sql.*;

public class DataBase {

    private static DataBase database;
    private static final String dbName = "Storage";

    private Connection conn;

    public static DataBase getInstance(){
        if(database==null){
            database = new DataBase();
        }
        return database;
    }

    private DataBase() {
        init();
    }

    private void init(){
        try {
            Class.forName("org.sqlite.JDBC");
            conn = DriverManager.getConnection("jdbc:sqlite:" + dbName);
            createTablesIfNotExist();
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
    }

    private void createTablesIfNotExist() throws SQLException {
        Statement st = conn.createStatement();
        st.execute(Queries.ENABLE_FOREIGN_KEY);
        st.execute(Queries.CREATE_TABLE_GROUP);
        st.execute(Queries.CREATE_TABLE_PRODUCT);
        st.execute(Queries.CREATE_TABLE_USER);
//        st.execute("insert into user values (1, 'user', '4297f44b13955235245b2497399d7a93')"); //123123 - password
        st.close();
    }

    public Statement createStatement() throws SQLException {
        return conn.createStatement();
    }

    public PreparedStatement prepareStatement(String query) throws SQLException {
        return conn.prepareStatement(query);
    }

    public PreparedStatement prepareStatement(String query, int autoGeneratedKeys) throws SQLException {
        return conn.prepareStatement(query, autoGeneratedKeys);
    }

    public boolean getAutoCommit() throws SQLException {
        return conn.getAutoCommit();
    }

    public void setAutoCommit(boolean autoCommit) throws SQLException {
        conn.setAutoCommit(autoCommit);
    }

    public void commit() throws SQLException {
        conn.commit();
    }

    public void rollback() throws SQLException {
        conn.rollback();
    }
}
